[mgr]
ratio        = [1, 3, 4]      # Pane width ratios [parent, current, preview]
sort_by      = "natural"       # natural, mtime, extension, alphabetical, size
sort_dir_first = true          # Directories listed before files
show_hidden  = false           # Show dotfiles
scrolloff    = 5               # Cursor padding from edge
linemode     = "size"          # none, size, mtime, permissions, owner

[preview]
wrap = "yes"
tab_size = 2
max_width = 1000
max_heght = 1000
image_filter = "lanczos3"
image_quality = 90

[plugin]
prepend_fetchers = [
  { group = "git", url = "*", run = "git" }
]
prepend_previewers = [
  { url = "*.tar*", run = 'piper --format=url -- tar tf "$1"' },
  { url = "*.csv", run = 'piper -- bat -p --color=always "$1"' },
  { url = "*.md", run = 'piper -- CLICOLOR_FORCE=1 glow -w=$w -s=dark "$1"' },
  { url = "*/", run = 'piper -- eza -TL=3 --color=always --icons=always --group-directories-first --no-quotes "$1"' }
#  { url = "*", run =  'piper -- hexyl --border=none --terminal-width=$w "$1"' }
]

